version: '3'

services:

  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: companydb
    ports:
      - "3307:3306"

  backend:
    build: ./backend
    container_name: backend-container
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: frontend-container
    ports:
      - "3000:3000"
    depends_on:
      - backend